### PR TITLE
Scrub snmp session args.

### PR DESCRIPTION
**Pull request by mullagain**
Lets me stuff something to keep track of the request inside the scheduler.

### CODE REVIEW

**Comment by jhthorsen** [comment]
I'm not sure if I'm a huge fan of this. I don't want to maintain this list internally, and it seems fairly simple to fix from the outside. Do you have a usecase where this is needed? What happens if you try to pass on "invalid" keys to Net::SNMP?

**Comment by mullagain** [comment]
Net::SNMP does not allow invalid keys, the program will die. I am working on building a state based snmp poller. I wanted to have a hash of nodes with their state, and once I get a reply I can map the reply to the node/state.

**Comment by jhthorsen** [comment]
I will take this pull request with some modifications if you write some tests.

**Comment by jhthorsen** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
